# Site settings
title: Eat Code Love
header-img: img/home-bg.png
email: johnsont426@gmail.com
copyright_name: johnsont426
description: > # this means to ignore newlines until "baseurl:"
  Coding—My New Lifestyle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  johnsont426
learn_profile: johnsont426
email_username: johnsont426@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
